### ISSUE TITLE
Python 3.12 compatibility

### ISSUE THREAD

**Issue by Selur** [SAPikachu/flash3kyuu_deband#11]
When building with Python 3.12 I get:
```
Klone nach 'build' …
Submodul 'lib/googletest' (https://github.com/SAPikachu/googletest.git) für Pfad 'lib/googletest' in die Konfiguration eingetragen.
Klone nach '/home/selur/workspace/hybrid-vapoursynth-addon/build/build/lib/googletest' …
Submodul-Pfad 'lib/googletest': '90d1e5432bec96898b48bfb738a46578ee35aea0' ausgecheckt
/home/selur/workspace/hybrid-vapoursynth-addon/build/build/.waf3-2.0.10-195b3fea150563357014bcceb6844e0e/waflib/Utils.py:438: SyntaxWarning: invalid escape sequence '\d'
  return re.split('\d+$',s)[0]
/home/selur/workspace/hybrid-vapoursynth-addon/build/build/.waf3-2.0.10-195b3fea150563357014bcceb6844e0e/waflib/ConfigSet.py:7: SyntaxWarning: invalid escape sequence '\ '
  re_imp=re.compile('^(#)*?([^#=]*?)\ =\ (.*?)$',re.M)
/home/selur/workspace/hybrid-vapoursynth-addon/build/build/.waf3-2.0.10-195b3fea150563357014bcceb6844e0e/waflib/ansiterm.py:178: SyntaxWarning: invalid escape sequence '\['
  ansi_tokens=re.compile('(?:\x1b\[([0-9?;]*)([a-zA-Z])|([^\x1b]+))')
Traceback (most recent call last):
  File "/home/selur/workspace/hybrid-vapoursynth-addon/build/build/./waf", line 164, in <module>
    from waflib import Scripting
  File "/home/selur/workspace/hybrid-vapoursynth-addon/build/build/.waf3-2.0.10-195b3fea150563357014bcceb6844e0e/waflib/Scripting.py", line 7, in <module>
    from waflib import Utils,Configure,Logs,Options,ConfigSet,Context,Errors,Build,Node
  File "/home/selur/workspace/hybrid-vapoursynth-addon/build/build/.waf3-2.0.10-195b3fea150563357014bcceb6844e0e/waflib/Configure.py", line 6, in <module>
    from waflib import ConfigSet,Utils,Options,Logs,Context,Build,Errors
  File "/home/selur/workspace/hybrid-vapoursynth-addon/build/build/.waf3-2.0.10-195b3fea150563357014bcceb6844e0e/waflib/Options.py", line 6, in <module>
    from waflib import Logs,Utils,Context,Errors
  File "/home/selur/workspace/hybrid-vapoursynth-addon/build/build/.waf3-2.0.10-195b3fea150563357014bcceb6844e0e/waflib/Context.py", line 5, in <module>
    import os,re,imp,sys
ModuleNotFoundError: No module named 'imp'
```
from what I understand, 'imp' was removed and instead 'importlib' needs to be used starting with Python 3.12
Would be nice if flash3kyuu_deband  so that I can also be build with Python 3.12 since that is the current Python Vapoursynth 68+ support.

**Comment by SAPikachu** [comment]
Sorry, I haven't worked on this for a long time, maybe you can check the successor version at https://github.com/HomeOfAviSynthPlusEvolution/neo_f3kdb , which should have better support of new toolchains.

**Comment by Selur** [comment]
Okay, no problem. I'll try [neo_f3kdb](https://github.com/HomeOfAviSynthPlusEvolution/neo_f3kdb), I usually prefer to have both as an option, since from time to time user otherwise complain that they neo doesn't work, which usually is due to the SSE4.1  requirement.
Thanks for letting me know.

**Comment by msg7086** [comment]
I think SSE4.1 is popular enough for today. Latest Windows 11 will require SSE4.2 to even boot.

**Comment by Selur** [comment]
Yeah, no problem, just need to adjust some scripts to use the neo variant. :)
